name: Pruebas de Unidad

# eventos
on:
  push:
    branches: [ master ]  # combino los datos en master
  pull_request:
    branches: [ master ]  # cuando hay pull request
  workflow_dispatch:      # cuando hago clic en un botón
  

# stages -> jobs
# jobs
jobs:

  hola-mundo:
        
    runs-on: ubuntu-latest

    steps:
      # utiliza un componente que se llama actions
      - name: descargar el código fuente 
        uses: actions/checkout@v2

      - name: Setup Java JDK
          uses: actions/setup-java@v2.3.1
          with:
            java-version: 11
            distribution: 'adopt'
            java-package: jdk

      - name: Compila el proyecto y ejecuta las pruebas
        run: mvn -B package --file pom.xml

