name: Ejemplo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  Ejemplo:
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [11, 12]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: descarga el codigo fuente
        uses: actions/checkout@v2
        
      - name: Configura el Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: ${{ matrix.java }}      

      - name: Compila el proyecto
        run: mvn -B package --file pom.xml
